title: Yi Yi
description: Writings by Yi Yi
author: Yi Yi
url: https://yiyistory.github.io
permalink: /:year/:month/:title/
timezone: Asia/Shanghai
future: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
exclude:
  - README.md
  - 写作说明.md
